type App = {
  type: "app" | "integration",
  displayName: string,
  subtitle: string,
  tags: string[],
  stage: "alpha" | "beta" | "stable",
};

export const ALL_APPS = {
  "authentication": {
    type: "app",
    displayName: "Authentication",
    subtitle: "User sign-in and account management",
    tags: ["auth", "security"],
    stage: "stable",
  },
  "teams": {
    type: "app",
    displayName: "Teams",
    subtitle: "Team collaboration and management",
    tags: ["collaboration", "organization"],
    stage: "stable",
  },
  "rbac": {
    type: "app",
    displayName: "RBAC",
    subtitle: "Role-based access control and permissions",
    tags: ["security", "permissions"],
    stage: "stable",
  },
  "api-keys": {
    type: "app",
    displayName: "API Keys",
    subtitle: "API key generation and management",
    tags: ["api", "security"],
    stage: "stable",
  },
  "payments": {
    type: "app",
    displayName: "Payments",
    subtitle: "Payment processing and subscription management",
    tags: ["billing", "monetization"],
    stage: "stable",
  },
  "emails": {
    type: "app",
    displayName: "Emails",
    subtitle: "Email template configuration and management",
    tags: ["communication", "templates"],
    stage: "stable",
  },
  "email-api": {
    type: "app",
    displayName: "Email API",
    subtitle: "Programmatic email sending and delivery",
    tags: ["api", "communication"],
    stage: "alpha",
  },
  "data-vault": {
    type: "app",
    displayName: "Data Vault",
    subtitle: "Secure storage for sensitive user data",
    tags: ["security", "storage"],
    stage: "stable",
  },
  "workflows": {
    type: "app",
    displayName: "Workflows",
    subtitle: "Automated business process orchestration",
    tags: ["automation", "processes"],
    stage: "beta",
  },
  "webhooks": {
    type: "app",
    displayName: "Webhooks",
    subtitle: "Real-time event notifications and integrations",
    tags: ["integration", "events"],
    stage: "stable",
  },
  "tv-mode": {
    type: "app",
    displayName: "TV mode",
    subtitle: "Dashboard display for large screens",
    tags: ["display", "monitoring"],
    stage: "alpha",
  },
  "launch-checklist": {
    type: "app",
    displayName: "Launch Checklist",
    subtitle: "Pre-launch verification and readiness checks",
    tags: ["deployment", "verification"],
    stage: "alpha",
  },
  "catalyst": {
    type: "app",
    displayName: "Catalyst",
    subtitle: "Project scaffolding and rapid development",
    tags: ["development", "tooling"],
    stage: "alpha",
  },
  "neon": {
    type: "integration",
    displayName: "Neon",
    subtitle: "Serverless Postgres database integration",
    tags: ["database", "integration"],
    stage: "alpha",
  },
  "convex": {
    type: "integration",
    displayName: "Convex",
    subtitle: "Real-time backend platform integration",
    tags: ["database", "integration", "realtime"],
    stage: "alpha",
  },
} as const satisfies Record<string, App>;
